### ISSUE TITLE
Small regex mistake

### ISSUE THREAD

**Issue by nicolasmol** [mondersky/tabscolor-vscode#15]
```javascript
replace(/\\?refresh=\d/, "") + "?refresh=" + Math.floor(Math.random() * 11
```
Will give this kind of mistake:

```html
vscode-file://vscode-[...]/inject.css?refresh=9?refresh=7?refresh=11?refresh=5
```
I think the correct regex is:
`
/\?refresh=\d/
`
BTW: why (11) eleven ?

**Comment by mondersky** [comment]
Thanks for pointing me out to this issue
The right string is /\\?refresh=\\d/
I am using \\ rather than \ because the regex is being written to a js file first before it gets executed, this is to escape the \ character itself. So we end up by having the regex you mentioned yourself /\?refresh=\d/
https://github.com/mondersky/tabscolor-vscode/blob/e97fcc33f0e0420e88f4de243fa0b99dcd6950f8/extension.js#L313
