### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by e7o-de** [mondersky/tabscolor-vscode#29]
Hey,

I stumpled over your extension as I was looking for exactly such a thing. Unfortunately, I'm not (easily) able to color my tabs based on directories for now, as I'm using VS Code on different machines with sync of my settings. Now ... the thing is that there are different paths, like /home/super-work-user/webprojects/www at work and /home/personal/www on private. Is it possible to get something like placeholders in the by directory coloring rules?

Thx & best wishes

**Comment by mondersky** [comment]
Currently, the extension does not support variables or placeholders in the settings. However, you can achieve a similar result by using portions of paths instead of absolute ones. For instance:
```
"tabsColor.byDirectory": {
  "www": {
    "backgroundColor": "red",
    "fontColor": "#000000"
  }
}
```
With this configuration, the tab of any file whose path includes "www" will be colored, making it effective for both 'user1\www' and 'user2\www' simultaneously

**Comment by e7o-de** [comment]
Thank you very much for your reply. Actually, this works at least for one use case when I'm not using ~ or such things for my home directory.

Keep up the good work!
