### ISSUE TITLE
unable patch color - windows remote ssh project

### ISSUE THREAD

**Issue by TomNovy81** [mondersky/tabscolor-vscode#31]
I added your extension on windows on remote ssh project, when I choose a color it writes: unable patch color
Plase could you fix it?

**Comment by xxxxxxbox** [comment]
The same here.
Cant' use Tabs color with remote SSH tabs.
Please fixed it.

**Comment by mondersky** [comment]
version 2.3 should support SSH tabs, can you please confirm if this works on your end ?

**Comment by xxxxxxbox** [comment]
I've tested SSH Tabs with v.0.2.4.

1. SSH Tabs change colors but only VS Code restart, The issue is the same as issue in local environment https://github.com/mondersky/tabscolor-vscode/issues/34

Some more observations:
2. When colored SSH tab is moved to splitted area it remains colored as expected.
3. But when colored SSH tab is moved to separate window it reset it's color to default. When the tab is  moved back to first window it becomes colored again,

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

Remote SSH host - Debian.

**Comment by mondersky** [comment]
@xxxxxxbox follow the the separate window issue here #40
